"""Minimum fan airflow (CFM) to cool the VRB resistor bank in its worst case.

Worst case
----------
The full 8 kW is dissipated by the top row alone. At the ladder's 0.25 ohm
floor only Bank 1 is in circuit, and Bank 1 is the four 1 ohm TE2000B elements
that form the top row (docs/hardware_topology.md). The rows beneath are
physically present -- they trip the airflow and set the turbulence the top row
sees -- but they carry no current and add no heat.

So the geometry splits in two:

  * Aerodynamics uses the WHOLE array: 3 rows, 11 tubes. Face velocity, the
    maximum velocity between tubes, the Reynolds number and the Zukauskas row
    correction C2 all come from the full tube bank sitting in the duct. The
    correlation sees the array only through its pitches and row count, so the
    tube count itself never enters.
  * Thermodynamics uses only the HEATED tubes: the area that has to shed the
    8 kW is active_heated_resistors x one element's area, not all 11.

Boundary condition
------------------
A resistor is a heat source, not a thermostat: it produces 8 kW whatever its
temperature, and its surface settles wherever that heat can escape. So the heat
is fixed and the surface temperature is the unknown. For a given CFM this script
computes the resulting surface temperature of the active row, then root-finds
the CFM at which that temperature just reaches the limit.

Conventions and assumptions
---------------------------
  * CFM is the fan's volumetric flow at inlet (ambient) conditions. The fan sits
    below the bank blowing upward, so it moves unheated air.
  * The rig is at altitude (SITE_PRESSURE_RATIO, 0.846 for Provo). The same CFM
    carries ~18% less mass than at sea level, so every required CFM is ~18%
    higher than a sea-level calculation would say.
  * Air flows upward, so the top row is the LAST row the air meets. The 3-row C2
    (0.84) is an average over all rows, and a downstream row runs above that
    average. Applying the average to the top row underestimates its h, which is
    conservative. If the airflow were ever reversed the heated row would be the
    first, whose own C2 is 0.64, and this model would be optimistic.
  * Radiation is neglected. At 450 K it could carry up to roughly a tenth of the
    load, so ignoring it overstates the surface temperature -- conservative.
  * The Zukauskas correlation is for smooth cylinders. The 2 kW TE elements are
    ribbed (edge-wound); their smooth envelope area stands in for the heated area.
  * The Zukauskas fit switches constants at Re_D = 2e5 and Nu jumps ~22% there.
    That is a curve-fit artefact, not physics. The default answer sits at
    Re_D ~ 1.5e5, clear of it; answers that land on it are flagged.
  * 450 K is a design limit, not the resistor's. The TE datasheet's temperature
    rise chart puts the element about 370 C above ambient at full rated load in
    free air; its 155 C figure is an AMBIENT limit on the derating curve.
  * Air properties come from Gas_Properties_ATMP.csv (300-1000 K, Incropera
    Table A.4; rows above 600 K added for the hot-surface cases). The answer is
    always evaluated inside that range; air_properties() explains how the solver
    steps through infeasible flows that fall outside it.
"""

import math
import os

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import root_scalar

# --- Tube-bank geometry: the WHOLE array. Sets the aerodynamics. ---
# Kept global so helper functions can access them without needing them passed every time
D = 0.060           # element outer diameter, m (TE 1000-2500 W parts: 60 mm)
ST = 0.124          # transverse pitch, m
SL = 0.152          # longitudinal (row-to-row) pitch, m
SD = 0.165          # diagonal pitch, m -- sqrt(SL^2 + (ST/2)^2) = 0.164; measured 0.165
NL = 3              # rows in the flow direction, heated or not
duct_area = 0.61 * 0.61  # 2ft x 2ft in m^2
A_cylinder = 0.094       # heated surface area of ONE element, m^2 (pi x 0.060 m x ~0.50 m)

# --- Worst-case operating point ---
Q_TARGET_W = 8000.0           # heat generated by the active row -- fixed, not solved for
T_IN_K = 300.0                # ambient air entering the fan
T_S_MAX_K = 450.0             # design limit on the active row's mean surface temperature
ACTIVE_HEATED_RESISTORS = 4   # Bank 1: 4 x TE2000B 1 ohm, the top row
TUBES_IN_ACTIVE_ROW = 4       # the model heats a single row, so this caps the line above
BYPASS_FRACTION = 0.10        # share of the airflow that skirts the array along the walls

# Air pressure at the rig over sea-level pressure. The gas table is at 1 atm; the
# rig is in Provo, ~1390 m up, where the standard atmosphere gives 0.846. Only
# density scales with it -- viscosity, conductivity, cp and Pr do not -- and a fan
# moves the same VOLUME at altitude, so thinner air means ~18% less MASS through
# the bank for the same CFM. Set 1.0 for sea level.
SITE_PRESSURE_RATIO = 0.846

CFM_TO_M3S = 0.000471947

# Validity window for the Zukauskas fit used in calc_Nu_D. Below 10^3 neither
# the m = 0.6 constants nor the C2 row-correction table apply.
ZUKAUSKAS_RE_MIN = 1e3
ZUKAUSKAS_RE_MAX = 2e6

# Where the fit switches from m = 0.6 to m = 0.84. Nu steps up about 22% across
# it -- an artefact of piecewise curve fits, not physics.
ZUKAUSKAS_RE_SWITCH = 2e5

# Convergence tolerance for the fixed-point loop. It has to sit ABOVE the noise
# floor of the property table: get_gas_properties rounds every property to six
# decimals, so Pr and cp are staircases, and a temperature sitting near a step
# can flip between two neighbouring values forever. The flip is a fixed
# fraction of the temperature rise (seen: ~1e-7 of it), so the tolerance is an
# absolute floor plus a relative part -- an absolute tolerance alone fails at
# the huge rises the bracket search visits at tiny flows.
T_TOL_K = 1e-3
T_TOL_REL = 1e-5


def get_gas_properties(temp_k):
    """
    Interpolates gas properties from a CSV file for a given temperature.
    """
    file_path = r"C:\Users\Durbi\PycharmProjects\Resistor Bank Master\Gas_Properties_ATMP.csv"

    try:
        df = pd.read_csv(file_path)
        df.columns = df.columns.str.strip()
        t_values = df['T (K)'].values

        if temp_k < t_values.min() or temp_k > t_values.max():
            return {
                "Error": f"Temperature {temp_k}K is outside the data range ({t_values.min()}K - {t_values.max()}K)."}

        interpolated_data = {}
        for column in df.columns:
            if column == 'T (K)':
                interpolated_data[column] = float(temp_k)
            else:
                val = np.interp(temp_k, df['T (K)'], df[column])
                interpolated_data[column] = round(val, 6)

        return interpolated_data

    except FileNotFoundError:
        return {"Error": "The CSV file was not found at the specified path."}
    except Exception as e:
        return {"Error": str(e)}


# The table's range, read once for its bounds only. The interpolation itself
# stays in get_gas_properties.
_gas_table = pd.read_csv(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                      "Gas_Properties_ATMP.csv"))
_gas_table.columns = _gas_table.columns.str.strip()
T_TABLE_MIN_K = float(_gas_table['T (K)'].min())
T_TABLE_MAX_K = float(_gas_table['T (K)'].max())


def air_properties(temp_k):
    """Air properties at temp_k in SI units, plus whether temp_k had to be clamped.

    Clamping exists for the solver, not the answer. While bracketing, the solver
    tries flows far too small to cool the bank, where the air or the surface runs
    off the top of the table. A property is only clamped when the temperature
    asking for it is above the table's top -- and the surface is hotter than the
    air, so at any such point the surface is above it too, beyond any limit this table
    can check. The residual's sign is therefore right at every clamped point,
    which is all bracketing needs, and clamping adds no discontinuity of its own.
    find_CFM's input checks keep the answer itself inside the table, and it warns
    if that ever fails.
    """
    t = min(max(temp_k, T_TABLE_MIN_K), T_TABLE_MAX_K)
    raw = get_gas_properties(t)
    if "Error" in raw:
        raise ValueError(f"Gas property lookup failed at {t} K: {raw['Error']}")
    return {
        "rho": raw['rho (kg/m3)'],
        "cp": raw['Cp (kJ/kg K)'] * 1e3,
        "mu": raw['mu*10^7 (N s/m2)'] * 1e-7,
        "k": raw['k*10^3 (W/m K)'] * 1e-3,
        "Pr": raw['Pr'],
        "clamped": t != temp_k,
    }


# --- Helper Functions ---
def calc_V_max(V):
    """Peak velocity between tubes, from the face velocity V ahead of the array.

    For a staggered bank it occurs in the diagonal gap if that gap is the
    narrower passage, otherwise in the transverse gap. Here 2(SD - D) = 0.210 m
    against ST - D = 0.064 m, so it is the transverse gap.
    """
    if 2 * (SD - D) < (ST - D):
        V_max = (ST / (2 * (SD - D))) * V
    else:
        V_max = (ST / (ST - D)) * V
    return V_max


def calc_Re_D(G_max, mu):
    """Reynolds number on diameter, from mass flux through the minimum flow area.

    The textbook form is V_max * D / nu with every property at T_mean. Written
    out, rho(T_mean) appears in both V_max (volume flow swells as air heats) and
    in nu = mu / rho, and cancels. What is left is G_max * D / mu(T_mean), with
    G_max = rho * V_max conserved along the flow. Using this form avoids the
    trap of taking V from a CFM measured at the fan but nu at a different
    temperature, which undercounts Re by rho_mean / rho_inlet.
    """
    return G_max * D / mu


def calc_Nu_D(Re_D, Pr, Pr_s, n_rows=NL):
    """Zukauskas mean Nusselt number for a staggered tube bank of n_rows rows."""
    if Re_D < ZUKAUSKAS_RE_SWITCH:
        m = 0.6
        if ST / SL < 2:
            C1 = 0.35 * ((ST / SL) ** 0.2)
        elif ST / SL > 2:
            C1 = 0.4
        else:
            C1 = 0.4  # Fallback if exactly 2
    else:
        m = 0.84
        C1 = 0.022

    # Map NL to C2
    nl_mapping = {
        1: 0.64, 2: 0.76, 3: 0.84, 4: 0.89, 5: 0.92,
        6: (0.95 + 0.92) / 2, 7: 0.95
    }

    if n_rows in nl_mapping:
        C2 = nl_mapping[n_rows]
    elif 7 < n_rows < 10:
        C2 = 0.96
    elif 10 <= n_rows < 13:
        C2 = 0.97
    elif 13 <= n_rows < 16:
        C2 = 0.98
    elif 16 <= n_rows < 20:
        C2 = 0.99
    else:
        C2 = 1

    Nu_D = C2 * C1 * (Re_D ** m) * (Pr ** 0.36) * ((Pr / Pr_s) ** 0.25)
    return Nu_D


# --- Physics: surface temperature at a given airflow ---
def surface_temperature(CFM, active_heated_resistors=ACTIVE_HEATED_RESISTORS,
                        target_power_W=Q_TARGET_W, T_in_K=T_IN_K,
                        bypass_fraction=BYPASS_FRACTION, tol_K=T_TOL_K, max_iter=200):
    """Mean surface temperature of the active row when it dissipates target_power_W.

    Returns a dict of the converged state. The two temperature relations are:

        energy balance:   Q = m_dot * cp * (T_exit - T_in)
        heat transfer:    (T_s - T_exit) / (T_s - T_in) = exp(-NTU),
                          NTU = h * A_s / (m_dot * cp)

    The second is the log-mean-temperature-difference relation Q = h A LMTD,
    rearranged so T_s comes out in closed form:

        T_s = T_in + Q / (m_dot * cp * (1 - exp(-NTU)))

    Properties depend on T_exit (bulk, at the row's mean air temperature) and on
    T_s (Pr_s), so the two are iterated together to a fixed point. Both
    dependencies are weak, but the loop only settles to within the gas table's
    rounding noise -- see T_TOL_K -- not to machine precision.
    """
    if CFM <= 0:
        raise ValueError(f"CFM must be positive, got {CFM}")

    A_s = active_heated_resistors * A_cylinder           # THERMAL area: heated tubes only
    inlet = air_properties(T_in_K)

    # Mass is conserved through the bank; volume is not, because the air
    # expands as it heats. So fix the mass flow once, at the fan, where the CFM
    # is actually defined -- and only the core share, since bypass air never
    # touches a tube.
    vol_total_m3s = CFM * CFM_TO_M3S
    vol_core_m3s = vol_total_m3s * (1 - bypass_fraction)
    rho_site = inlet["rho"] * SITE_PRESSURE_RATIO        # the table is at 1 atm; the rig is not
    m_dot_core = rho_site * vol_core_m3s
    m_dot_total = rho_site * vol_total_m3s

    # AERODYNAMIC geometry: whole-array pitches, core flow only.
    V_core = vol_core_m3s / duct_area                    # face velocity, at inlet density
    V_max = calc_V_max(V_core)
    G_max = rho_site * V_max                             # mass flux through the minimum area

    # Air reaches the top row at T_in: the rows below it are unpowered.
    T_exit = T_in_K + 1.0
    T_s = T_in_K + 1.0
    for _ in range(max_iter):
        bulk = air_properties(0.5 * (T_in_K + T_exit))   # across the active row only
        surf = air_properties(T_s)

        Re_D = calc_Re_D(G_max, bulk["mu"])
        Nu_D = calc_Nu_D(Re_D, bulk["Pr"], surf["Pr"], NL)
        h = Nu_D * bulk["k"] / D

        mcp = m_dot_core * bulk["cp"]
        ntu = h * A_s / mcp
        T_exit_new = T_in_K + target_power_W / mcp
        T_s_new = T_in_K + target_power_W / (mcp * -math.expm1(-ntu))  # expm1: exact at small NTU

        settled = (abs(T_s_new - T_s) < tol_K + T_TOL_REL * (T_s_new - T_in_K)
                   and abs(T_exit_new - T_exit) < tol_K + T_TOL_REL * (T_exit_new - T_in_K))
        T_s, T_exit = T_s_new, T_exit_new
        if settled:
            break
    else:
        raise RuntimeError(f"Surface temperature did not converge at {CFM} CFM")

    # Consistency check on the closed form above: re-derive Q from the LMTD
    # relation. When the T_s formula is coded right this is an identity, so it
    # guards the algebra, not the physics.
    dT_in, dT_out = T_s - T_in_K, T_s - T_exit
    lmtd = (dT_in - dT_out) / math.log(dT_in / dT_out)
    Q_check = h * A_s * lmtd

    return {
        "CFM": CFM,
        "T_surface_K": T_s,
        "T_core_exit_K": T_exit,
        "T_mixed_outlet_K": T_in_K + target_power_W / (m_dot_total * bulk["cp"]),
        "h_W_m2K": h,
        "Nu_D": Nu_D,
        "Re_D": Re_D,
        "V_face_m_s": vol_total_m3s / duct_area,
        "V_core_m_s": V_core,
        "V_max_m_s": V_max,
        "m_dot_core_kg_s": m_dot_core,
        "heated_area_m2": A_s,
        "heat_flux_W_m2": target_power_W / A_s,
        "Q_check_W": Q_check,
        "properties_clamped": bulk["clamped"] or surf["clamped"],
    }


# --- Main Function ---
def find_CFM(T_s_max_K=T_S_MAX_K, active_heated_resistors=ACTIVE_HEATED_RESISTORS,
             target_power_W=Q_TARGET_W, T_in_K=T_IN_K, bypass_fraction=BYPASS_FRACTION,
             cfm_lo=100.0, cfm_hi=1000.0, xtol_cfm=0.01):
    """Smallest CFM that keeps the active row's surface at or below T_s_max_K.

    Surface temperature never rises with airflow -- more air means both a cooler
    exit and a higher h -- so T_s(CFM) - T_s_max_K crosses zero at most once. But
    it can cross by jumping: Nu steps up ~22% where the Zukauskas fit changes
    constants at Re_D = 2e5, so T_s drops ~20-30 K in one step there. If the limit
    falls inside that step, no CFM puts T_s exactly on it, and the answer is the
    switch point itself; a warning says so. The bracket is widened until it
    straddles the crossing, then Brent's method closes it.

    Args:
        T_s_max_K: Allowable mean surface temperature of the active row, K.
        active_heated_resistors: Elements in the top row carrying the load.
        target_power_W: Heat the active row must dissipate, W.
        T_in_K: Ambient air temperature at the fan, K.
        bypass_fraction: Share of the flow that skirts the array, 0 <= b < 1.
        cfm_lo, cfm_hi: Starting bracket; widened automatically if needed.
        xtol_cfm: Absolute tolerance on the answer, CFM.

    Returns:
        dict: the converged state at the minimum CFM, plus a list of warnings.
    """
    if not 1 <= active_heated_resistors <= TUBES_IN_ACTIVE_ROW:
        raise ValueError(
            f"active_heated_resistors must be 1-{TUBES_IN_ACTIVE_ROW}. The model heats a "
            f"single row, and assumes the air reaches it unheated; heat in a second row "
            f"breaks that assumption.")
    if not 0 <= bypass_fraction < 1:
        raise ValueError(f"bypass_fraction must be in [0, 1), got {bypass_fraction}")
    if not T_TABLE_MIN_K <= T_in_K < T_s_max_K <= T_TABLE_MAX_K:
        raise ValueError(
            f"Need {T_TABLE_MIN_K:g} K <= T_in < T_s_max <= {T_TABLE_MAX_K:g} K "
            f"(the gas table's range); got T_in={T_in_K}, T_s_max={T_s_max_K}")

    kwargs = dict(active_heated_resistors=active_heated_resistors,
                  target_power_W=target_power_W, T_in_K=T_in_K,
                  bypass_fraction=bypass_fraction)

    def excess_K(CFM):
        return surface_temperature(CFM, **kwargs)["T_surface_K"] - T_s_max_K

    lo, hi = cfm_lo, cfm_hi
    while excess_K(hi) > 0:
        hi *= 2
        if hi > 1e7:
            raise RuntimeError("No realistic airflow reaches the limit -- check the inputs")
    while excess_K(lo) < 0:
        lo /= 2
        if lo < 1e-3:
            raise RuntimeError("Limit is met at vanishing airflow -- check the inputs")

    print(f"Solving for the CFM that holds {active_heated_resistors} heated resistor(s) "
          f"at {T_s_max_K:g} K with {target_power_W:g} W ...")
    sol = root_scalar(excess_K, bracket=[lo, hi], method="brentq", xtol=xtol_cfm)
    if not sol.converged:
        raise RuntimeError(f"Root finder did not converge: {sol.flag}")

    # The residual has a step in it: Nu jumps ~22% where the Zukauskas fit
    # switches constants at Re_D = 2e5. If the root falls inside that step,
    # brentq converges onto the jump and may hand back the side that still runs
    # too hot. Nudge upward onto the side that meets the limit, so the answer is
    # always a CFM that actually satisfies T_s <= T_s_max.
    CFM = sol.root
    result = surface_temperature(CFM, **kwargs)
    for _ in range(1000):
        if result["T_surface_K"] <= T_s_max_K + T_TOL_K:
            break
        CFM += xtol_cfm
        result = surface_temperature(CFM, **kwargs)
    else:
        raise RuntimeError(f"Could not step onto the feasible side of {sol.root:.2f} CFM")

    warnings = []
    shortfall_K = T_s_max_K - result["T_surface_K"]
    if shortfall_K > 10 * T_TOL_K:
        warnings.append(
            f"The answer sits on the correlation's switch at Re_D = {ZUKAUSKAS_RE_SWITCH:.0e}, "
            f"where Nu steps ~22%: just below this CFM the surface runs over the limit, at it "
            f"the surface is {shortfall_K:.2f} K under. The CFM here is set by the curve-fit's "
            f"discontinuity, so treat it as uncertain by roughly that step.")
    if result["properties_clamped"]:
        warnings.append("Air properties were clamped at the answer -- extend the gas table")
    if not ZUKAUSKAS_RE_MIN <= result["Re_D"] <= ZUKAUSKAS_RE_MAX:
        warnings.append(f"Re_D = {result['Re_D']:.0f} is outside the correlation's "
                        f"{ZUKAUSKAS_RE_MIN:.0e}-{ZUKAUSKAS_RE_MAX:.0e} range")
    if abs(result["Q_check_W"] - target_power_W) > 1e-6 * target_power_W:
        warnings.append(f"Energy balance off: LMTD gives {result['Q_check_W']:.3f} W")
    result["warnings"] = warnings
    return result


def plot_cfm_effects(bypass_fraction=BYPASS_FRACTION):
    # --- 1. Effect of how many top-row elements share the load ---
    # Surface limit held at T_S_MAX_K. Fewer elements means more heat flux each.
    resistor_range = list(range(1, TUBES_IN_ACTIVE_ROW + 1))
    cfm_by_resistors = []

    print("Calculating effect of heated resistor count...")
    for r in resistor_range:
        try:
            res = find_CFM(active_heated_resistors=r, bypass_fraction=bypass_fraction)
            cfm_by_resistors.append(res['CFM'])
        except Exception as e:
            print(f"Skipping {r} resistors due to error: {e}")
            cfm_by_resistors.append(None)

    # --- 2. Effect of the allowable surface temperature ---
    # Heated resistors held at ACTIVE_HEATED_RESISTORS. Capped at the gas table's top.
    temp_range = list(range(350, int(T_TABLE_MAX_K) + 1, 10))
    cfm_by_temp = []

    print("\nCalculating effect of surface temperature limit...")
    for t in temp_range:
        try:
            res = find_CFM(T_s_max_K=t, bypass_fraction=bypass_fraction)
            cfm_by_temp.append(res['CFM'])
        except Exception as e:
            print(f"Skipping {t}K due to error: {e}")
            cfm_by_temp.append(None)

    # --- 3. Plotting and Saving the Results ---
    print("\nGenerating and saving plots...")

    # Plot 1: Resistors vs CFM
    plt.figure(figsize=(8, 6))
    plt.plot(resistor_range, cfm_by_resistors, marker='o', color='b', linestyle='-', linewidth=2)
    plt.xlabel('Heated Resistors in the Top Row', fontsize=12)
    plt.ylabel('Minimum Required CFM', fontsize=12)
    plt.xticks(resistor_range)
    plt.grid(False)
    plt.tight_layout()

    resistor_filename = 'CFM_vs_Resistor_Count.png'
    plt.savefig(resistor_filename, dpi=300)
    plt.close()
    print(f"Saved: {os.path.abspath(resistor_filename)}")

    # Plot 2: Temperature vs CFM
    plt.figure(figsize=(8, 6))
    plt.plot(temp_range, cfm_by_temp, marker='s', color='r', linestyle='-', linewidth=2, markersize=5)
    plt.xlabel('Allowable Surface Temperature (K)', fontsize=12)
    plt.ylabel('Minimum Required CFM', fontsize=12)
    plt.grid(False)
    plt.tight_layout()

    temp_filename = 'CFM_vs_Surface_Temp.png'
    plt.savefig(temp_filename, dpi=300)
    plt.close()
    print(f"Saved: {os.path.abspath(temp_filename)}")


def print_report(r):
    print(f"\n  Minimum airflow            {r['CFM']:9.1f} CFM   (at the fan, incl. bypass)")
    print(f"  Active-row surface         {r['T_surface_K']:9.2f} K")
    print(f"  Core air leaving the row   {r['T_core_exit_K']:9.2f} K")
    print(f"  Mixed outlet (w/ bypass)   {r['T_mixed_outlet_K']:9.2f} K")
    print(f"  h                          {r['h_W_m2K']:9.2f} W/m^2K")
    print(f"  Re_D (at V_max)            {r['Re_D']:9.0f}")
    print(f"  Nu_D                       {r['Nu_D']:9.2f}")
    print(f"  Face velocity (total)      {r['V_face_m_s']:9.3f} m/s")
    print(f"  Core velocity / V_max      {r['V_core_m_s']:9.3f} / {r['V_max_m_s']:.3f} m/s")
    print(f"  Heated area / heat flux    {r['heated_area_m2']:9.3f} m^2 / {r['heat_flux_W_m2']:.0f} W/m^2")
    print(f"  Energy check (h A LMTD)    {r['Q_check_W']:9.2f} W")
    for w in r["warnings"]:
        print(f"  WARNING: {w}")


if __name__ == "__main__":
    # plot_cfm_effects()
    results = find_CFM()
    print_report(results)
